name: Gerar APK - IMPÉRIO GESTÃO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Criar estrutura Android
        run: flutter create --project-name imperio_gestao --platforms android .

      - name: Instalar dependências
        run: flutter pub get

      - name: Gerar APK
        run: flutter build apk --release

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: imperio-gestao-apk
          path: build/app/outputs/flutter-apk/app-release.apk
